"""initial schema

Revision ID: 13c7f0ebf33b
Revises:
Create Date: 2026-06-15 13:51:35.132371

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "13c7f0ebf33b"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "patients",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_patient_id", "patients", ["id"], unique=False)
    op.create_table(
        "devices",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("patient_id", sa.String(length=50), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("api_key_hash", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_device_api_key", "devices", ["api_key_hash"], unique=True)
    op.create_index("idx_device_patient", "devices", ["patient_id"], unique=False)
    op.create_index("idx_device_type", "devices", ["type"], unique=False)
    op.create_table(
        "measurements",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.String(length=50), nullable=False),
        sa.Column("patient_id", sa.String(length=50), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("device_type", sa.String(length=50), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "timestamp", name="uq_measurement_device_timestamp"),
    )
    op.create_index("idx_measurement_patient", "measurements", ["patient_id"], unique=False)
    op.create_index(
        "idx_measurement_patient_device_time",
        "measurements",
        ["patient_id", "device_type", "timestamp"],
        unique=False,
    )
    op.create_index("idx_measurement_timestamp", "measurements", ["timestamp"], unique=False)
    op.create_table(
        "alerts",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("measurement_id", sa.BigInteger(), nullable=False),
        sa.Column("patient_id", sa.String(length=50), nullable=False),
        sa.Column("device_type", sa.String(length=50), nullable=False),
        sa.Column("field", sa.String(length=50), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("rule", sa.String(length=100), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=True),
        sa.Column("resolved", sa.Boolean(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_by", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["measurement_id"],
            ["measurements.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("measurement_id", "rule", name="uq_alert_measurement_rule"),
    )
    op.create_index("idx_alert_patient", "alerts", ["patient_id"], unique=False)
    op.create_index("idx_alert_resolved", "alerts", ["resolved", "resolved_at"], unique=False)
    op.create_index("idx_alert_timestamp", "alerts", ["timestamp"], unique=False)
    op.create_table(
        "outbox",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("topic", sa.String(length=255), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("acked", sa.Boolean(), nullable=False),
        sa.Column("measurement_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["measurement_id"],
            ["measurements.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_outbox_acked", "outbox", ["acked"], unique=False)
    op.create_index("idx_outbox_created_at", "outbox", ["created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_outbox_created_at", table_name="outbox")
    op.drop_index("idx_outbox_acked", table_name="outbox")
    op.drop_table("outbox")
    op.drop_index("idx_alert_timestamp", table_name="alerts")
    op.drop_index("idx_alert_resolved", table_name="alerts")
    op.drop_index("idx_alert_patient", table_name="alerts")
    op.drop_table("alerts")
    op.drop_index("idx_measurement_timestamp", table_name="measurements")
    op.drop_index("idx_measurement_patient_device_time", table_name="measurements")
    op.drop_index("idx_measurement_patient", table_name="measurements")
    op.drop_table("measurements")
    op.drop_index("idx_device_type", table_name="devices")
    op.drop_index("idx_device_patient", table_name="devices")
    op.drop_index("idx_device_api_key", table_name="devices")
    op.drop_table("devices")
    op.drop_index("idx_patient_id", table_name="patients")
    op.drop_table("patients")
    # ### end Alembic commands ###
